### ISSUE TITLE
Add deals to widget UI

### ISSUE THREAD

**Issue by mrlundis** [bitrefill/airfill-widget#7]
### Background 

The Bitrefill/Airfill API (and bitrefill.com) exposes `deals` (time limited offers provided by operators) which should be available through the widget as well.

### Todo

- [ ] Design deal UI
- [ ] Implement deal UI
- [ ] Add option to disable deals if necessary
